services:
  web:
    build: .
    container_name: engine_app
    ports:
      - "8000:8000"
    restart: always

    env_file:
      - .env

    environment:
      - PYTHONUNBUFFERED=1

    volumes:
      - .:/app
      - db_data:/app/db

volumes:
  db_data:
