from .utils import is_ai_enabled
from .ai_router import generate_ai_content


def generate_article(keyword, style="blog"):

    # 🔍 DEBUG (remove later if needed)
    print("\n========== GENERATOR DEBUG ==========")
    print("AI ENABLED:", is_ai_enabled())
    print("KEYWORD:", keyword)

    # 🔥 CASE 1: AI ENABLED
    if is_ai_enabled():
        try:
            print("🚀 USING AI ROUTER...")

            content = generate_ai_content(keyword)

            print("✅ AI SUCCESS")

            return {
                "title": keyword,
                "content": content.strip(),
                "source": "AI"
            }

        except Exception as e:
            print("❌ AI ERROR:", str(e))
            return _dummy_article(keyword, error=str(e))

    # 🔥 CASE 2: AI DISABLED
    print("⚠️ USING DUMMY MODE")
    return _dummy_article(keyword)


# 🔧 DUMMY GENERATOR
def _dummy_article(keyword, error=None):

    title = f"[DUMMY] {keyword} - Test Article"

    content = f"""
🚨 THIS IS DUMMY CONTENT 🚨

Keyword: {keyword}

⚠️ This article is generated for testing only.
⚠️ AI SYSTEM DISABLED OR FAILED.

-------------------------------------

📌 Introduction:
This is a placeholder introduction for {keyword}.

📌 Explanation:
This content is NOT generated by AI.

📌 Features:
- Dummy content
- Debug friendly
- Safe fallback

📌 Conclusion:
Enable AI + valid API key to generate real content.

-------------------------------------

🔧 SYSTEM INFO:
Mode: DUMMY
"""

    return {
        "title": title,
        "content": content.strip(),
        "source": "DUMMY",
        "error": error
    }