# Generated by Django 6.0.4 on 2026-04-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_ai', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('AI', 'AI'), ('DUMMY', 'Dummy')], default='DUMMY', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
