# Generated by Django 6.0.4 on 2026-04-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_sitesettings_post_source_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('dummy', 'Dummy')], default='dummy', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='published_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('dummy', 'Dummy')], default='dummy', max_length=20),
        ),
    ]
