# Generated by Django 6.0.4 on 2026-04-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_canonical_url_post_excerpt_post_focus_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='keyword_density',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rank_prediction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='readability_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_auto_fix',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_rank_prediction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_seo',
            field=models.BooleanField(default=True),
        ),
    ]
